### ISSUE TITLE
イラスト素材をどうするか

### ISSUE THREAD

**Issue by mismith0227** [mismith0227/postcss-halloween#1]

**Comment by spicagraph** [comment]
イラスト素材の送り方を書いてくれるのが吉

**Comment by mismith0227** [comment]
@spicagraph 確かに！Readmeに追記しておきます

**Comment by mismith0227** [comment]
@spicagraph Readmeに追記しました！
こんな感じでいかがでしょう？？不明点あれば修正します。
https://github.com/mismith0227/postcss-halloween#イラスト提供してくれる方へ
